-- Schema initial PostgreSQL.
-- Reprend le modele precedemment genere par hibernate ddl-auto=update sous H2.
-- A partir d'ici, toute evolution du schema passe par une nouvelle migration Vn.

CREATE TABLE supplier (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    alias             VARCHAR(255),
    enterprise_number VARCHAR(255),
    category          VARCHAR(255)
);

CREATE TABLE app_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(255) NOT NULL UNIQUE,
    email               VARCHAR(255) NOT NULL UNIQUE,
    password            VARCHAR(255) NOT NULL,
    role                VARCHAR(255) NOT NULL,
    enabled             BOOLEAN      NOT NULL,
    ai_provider         VARCHAR(255),
    password_changed_at TIMESTAMP(6) NOT NULL,
    password_expires_at TIMESTAMP(6) NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL
);

CREATE TABLE invoice (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number            INTEGER      NOT NULL,
    sub_number        INTEGER,
    "year"            INTEGER      NOT NULL,
    type              VARCHAR(255) NOT NULL,
    supplier_id       BIGINT       NOT NULL,
    amount_inc_vat    NUMERIC(38, 2),
    amount_ex_vat     NUMERIC(38, 2),
    vat_amount        NUMERIC(38, 2),
    reception_date    DATE         NOT NULL,
    payment_date      DATE,
    peppol            BOOLEAN      NOT NULL,
    comment           VARCHAR(255),
    file_path         VARCHAR(255),
    date_scope        VARCHAR(255) NOT NULL,
    scope_date        DATE,
    file_detail       VARCHAR(255),
    created_by_id     BIGINT,
    falco_document_id VARCHAR(255) UNIQUE,
    CONSTRAINT uk_invoice_year_number_sub UNIQUE ("year", number, sub_number),
    CONSTRAINT fk_invoice_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id),
    CONSTRAINT fk_invoice_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id)
);

-- Index sur les criteres de recherche les plus frequents
CREATE INDEX idx_invoice_year ON invoice ("year");
CREATE INDEX idx_invoice_supplier ON invoice (supplier_id);
CREATE INDEX idx_invoice_reception_date ON invoice (reception_date);
