-- Depenses contractuelles sans document: loyer, frais bancaires, PLCI. Rien n'arrive
-- ni par Peppol ni par la boite de depot, il n'y a donc aucun PDF a attendre.
--
-- Deux notions distinctes sont introduites ici:
--   1. la serie de numerotation, qui separe ces lignes du facturier documente;
--   2. le modele recurrent, qui sert a engendrer les echeances a la demande.
-- La premiere s'utilise seule, pour une depense ponctuelle sans justificatif
-- (une amende, des frais de greffe): elle ne suppose pas la seconde.

-- 1. Serie de numerotation ------------------------------------------------

-- INVOICE: le facturier historique, une ligne = un document. EXPENSE: les
-- depenses sans document, numerotees a part (D001, D002...) pour que la serie
-- des documents reste continue et reste alignee sur ce qui part chez Falco.
ALTER TABLE invoice ADD COLUMN series VARCHAR(255);

UPDATE invoice SET series = 'INVOICE';

ALTER TABLE invoice ALTER COLUMN series SET NOT NULL;

-- L'unicite du numero est desormais relative a sa serie: 001 et D001 coexistent
-- la meme annee.
ALTER TABLE invoice DROP CONSTRAINT uk_invoice_year_number_sub;
ALTER TABLE invoice ADD CONSTRAINT uk_invoice_series_year_number_sub
    UNIQUE (series, "year", number, sub_number);

-- 2. Modele recurrent -----------------------------------------------------

CREATE TABLE recurring_expense (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label            VARCHAR(255) NOT NULL,
    supplier_id      BIGINT       NOT NULL,
    amount_inc_vat   NUMERIC(38, 2),
    amount_ex_vat    NUMERIC(38, 2),
    vat_amount       NUMERIC(38, 2),
    periodicity      VARCHAR(255) NOT NULL,
    start_date       DATE         NOT NULL,
    end_date         DATE,
    paid_on_due_date BOOLEAN      NOT NULL DEFAULT TRUE,
    comment          VARCHAR(255),
    file_detail      VARCHAR(255),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by_id    BIGINT       NOT NULL,
    CONSTRAINT fk_recurring_expense_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id),
    CONSTRAINT fk_recurring_expense_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id),
    CONSTRAINT ck_recurring_expense_period CHECK (end_date IS NULL OR end_date >= start_date)
);

-- 3. Lien echeance -> modele ----------------------------------------------

ALTER TABLE invoice ADD COLUMN recurring_expense_id BIGINT;
ALTER TABLE invoice ADD CONSTRAINT fk_invoice_recurring_expense
    FOREIGN KEY (recurring_expense_id) REFERENCES recurring_expense (id);

-- Une echeance engendree est toujours une depense sans document, et porte
-- toujours la date de debut de sa periode: c'est cette date qui identifie
-- l'echeance et empeche de la creer deux fois.
ALTER TABLE invoice ADD CONSTRAINT ck_invoice_recurring_is_expense
    CHECK (recurring_expense_id IS NULL OR (series = 'EXPENSE' AND scope_date IS NOT NULL));

-- Garde-fou contre le double clic sur "generer": l'unicite est en base, pas
-- seulement dans le service qui filtre les periodes deja engendrees.
CREATE UNIQUE INDEX uk_invoice_recurring_period
    ON invoice (recurring_expense_id, scope_date)
    WHERE recurring_expense_id IS NOT NULL;

CREATE INDEX idx_recurring_expense_supplier ON recurring_expense (supplier_id);
